### ISSUE TITLE
Unhandled exception error when trying to add a weapon modification to a weapon modification

### ISSUE THREAD

**Issue by fst0pped** [JonasTrampe/ChummerGenSR4#10]
**Reproduction**
Start with create new character > Street Gear Tab > Weapons
1. Add a weapon (e.g. Aers Predator V)
2. Add modification (e.g. Smartgun system)
3. Open 'add weapon' dropdown and click 'add modification'.

**Notes**
Add underbarrel weapon seems to handle this gracefully be defaulting the target to the parent weapon for a modification.

**Error details copy and paste**

_See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at Chummer.frmCreate.tsWeaponAddModification_Click(Object sender, EventArgs e) in D:\a\ChummerGenSR4\ChummerGenSR4\Chummer\code\frmCreate.cs:line 8688
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9181.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
ChummerGenSR4
    Assembly Version: 0.0.0.495
    Win32 Version: 0.0.0.495
    CodeBase: file:///C:/Users/andy_/Documents/ShadowRun/ChummerGenSR4/bin/ChummerGenSR4.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9181.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9206.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9200.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box._

**Comment by fst0pped** [comment]
Please let me know if you need anything else, this is the first time I've raised a github issue!

**Comment by JonasTrampe** [comment]
Oh, I did not see your issue, I will take a look into it.

**Comment by JonasTrampe** [comment]
Please test the binary here if I overlooked something: https://github.com/JonasTrampe/ChummerGenSR4/actions/runs/7063368448
(You find it if you scroll down, under artifacts)

**Comment by fst0pped** [comment]
I'm still seeing the bug in the file downloaded from artifacts. I tried using the windows steps recorder to show the workflow that leads to it.

On gear screen
1. Add weapon
2. Add modification to weapon
3. Select modification and click add modification from drop down

[weapon_mod_bug_steps.zip](https://github.com/JonasTrampe/ChummerGenSR4/files/13532827/weapon_mod_bug_steps.zip)

**Comment by fst0pped** [comment]
Easily done. Tried to replicate and got an dialogue box telling me modifications can't be added to the weapon, so no unhandled exception. All looks good 👍Thanks!

**Comment by JonasTrampe** [comment]
Fixed in https://github.com/JonasTrampe/ChummerGenSR4/releases/tag/v0.1.496
